### ISSUE TITLE
Attribute Providing Tutorial in Wiki does not work.

### ISSUE THREAD

**Issue by miladamery** [authzforce/core#24]
authzforce-ce-core-pdp-api 15.0.0

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

Windows 10
```
[ERROR] Error while parsing schema(s).Location [ file:/F:/IntelijWorkspace/pip/src/main/resources/org.baharan.PolicyInfoProvider.xsd{40,67}].
org.xml.sax.SAXParseException; systemId: file:/F:/IntelijWorkspace/pip/src/main/resources/org.baharan.PolicyInfoProvider.xsd; lineNumber: 40; columnNumber: 67; undefined simple or complex type 'authz-ext:AbstractPolicyProvider'
	at com.sun.xml.xsom.impl.parser.ParserContext$1.reportError(ParserContext.java:180)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.reportError(NGCCRuntimeEx.java:175)
	at com.sun.xml.xsom.impl.parser.DelayedRef.resolve(DelayedRef.java:110)
	at com.sun.xml.xsom.impl.parser.DelayedRef.run(DelayedRef.java:85)
	at com.sun.xml.xsom.impl.parser.ParserContext.getResult(ParserContext.java:135)
	at com.sun.xml.xsom.parser.XSOMParser.getResult(XSOMParser.java:214)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:538)
	at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:378)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:174)
	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:119)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.loadModel(XJC22Mojo.java:50)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:40)
	at org.jvnet.mjiip.v_2_2.XJC22Mojo.doExecute(XJC22Mojo.java:28)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.doExecute(RawXJC2Mojo.java:505)
	at org.jvnet.jaxb2.maven2.RawXJC2Mojo.execute(RawXJC2Mojo.java:328)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```
I Followed Exact Steps in https://github.com/authzforce/core/wiki/Attribute-Providers 
i even copied the same content from pdptestutils to just make it work but when i try to run 
generate-sources command from maven the top error comes.

**Comment by cdanger** [comment]
You may be facing the same issue as #23 .  I've just updated the wiki page. Make sure to apply the same changes to the configuration of the maven-jaxb2-plugin:
- Use v0.14.0 of the plugin
- Set `useDependenciesAsEpisodes`  to `true`
- Remove the `<episodes>` element
- Set `verbose` to `true` to get more info it it fails again and let me know.

**Comment by miladamery** [comment]
thanks. with these changes it worked and no error happened.
