### ISSUE TITLE
accessExternalSchema property can not be accessed in weblogic

### ISSUE THREAD

**Issue by miladamery** [authzforce/core#31]
<dependency>
           <groupId>org.ow2.authzforce</groupId>
           <artifactId>authzforce-ce-core-pdp-engine</artifactId>
           <version>13.2.0</version>
</dependency>

java version "1.8.0_131"

Windows 10

```
Caused By: org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 52; schema_reference: Failed to read schema document 'xml.xsd', because 'http' access is not allowed due to restriction set by the accessExternalSchema property. 
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaErr(XSDHandler.java:4156)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.reportSchemaFatalError(XSDHandler.java:4135)
	Truncated. see log file for complete stacktrace
```

I created a spring boot project and made effort to create authzForce engine in that, then creating requests in java api form. when i run this project on the embeded tomcat the line:
```
System.setProperty("javax.xml.accessExternalSchema", "http,file");
```
make access to http and file ok but when i run this project on weblogic the top error persists. i even tried 
```
<plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <jvmArguments>
                                -Djavax.xml.accessExternalSchema=all -Dfile.encoding=UTF8 -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
                            </jvmArguments>
                        </configuration>
                    </plugin>
```
but didn't work.

**Comment by cdanger** [comment]
Alas, it seems like Weblogic specific and I have zero experience with Weblogic. I can only suggest to try setting the JVM argument on Weblogic via [Weblogic configuration file or startup script (see the doc) ](https://docs.oracle.com/cd/E13222_01/wls/docs81/ConsoleHelp/startstop.html#1228952).
