### ISSUE TITLE
Problem resolving references in CoreRefPolicyProvider and PolicyEvaluator

### ISSUE THREAD

**Issue by wwebers** [authzforce/core#37]
# Software version (AuthzForce Core)
13.3.1
# Platform JRE
OpenJDK 11
# Platform OS
Windows 10
# Error stack trace or logs (if any)
`java.lang.IllegalArgumentException: Invalid PolicySet with PolicySetId='urn:dom:policyset:alfa:remus:process:forhandla', Version=1.0
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefPolicyProvider.<init>(CoreRefPolicyProvider.java:403)
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefPolicyProvider.getInstance(CoreRefPolicyProvider.java:678)
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefPolicyProvider$Factory.getInstance(CoreRefPolicyProvider.java:255)
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefPolicyProvider$Factory.getInstance(CoreRefPolicyProvider.java:130)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.newRefPolicyProvider(PdpEngineConfiguration.java:139)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.<init>(PdpEngineConfiguration.java:371)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:472)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:516)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:548)
Caused by: java.lang.IllegalArgumentException: No Policy matching reference: id = checkRoleRegistrerare, Optional[Version=*,EarliestVersion=*,LatestVersion=*]
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicyRefEvaluatorFactory.getInstance(PolicyEvaluators.java:1667)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicyRefEvaluatorFactory.getInstance(PolicyEvaluators.java:1640)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceGeneric(PolicyEvaluators.java:1704)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceStatic(PolicyEvaluators.java:1771)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicySetElementEvaluatorFactory.getChildPolicyRefEvaluator(PolicyEvaluators.java:1914)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators$StaticPolicySetElementEvaluatorFactory.getChildPolicyRefEvaluator(PolicyEvaluators.java:1852)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceGeneric(PolicyEvaluators.java:2111)
	at org.ow2.authzforce.core.pdp.impl.policy.PolicyEvaluators.getInstanceStatic(PolicyEvaluators.java:2305)
	at org.ow2.authzforce.core.pdp.impl.policy.CoreRefPolicyProvider.<init>(CoreRefPolicyProvider.java:398)
	... 69 more
`
# Your code and/or AuthzForce-specific configuration file(s)
I've a more complex setup where I have several policysets, each of them defining some policies and/or referencing to others externally defined. I took care to not create a circular dependency.

The root-policyset is just refering to all the other sets. When debugging authzforce-core I detect the folling behaviour:

**CoreRefPolicyProvider** read all policysets, but does not care about the containing policies. The table **updatablePolicyTable** remains empty. This mainly because the included policies are not parsed.

As a result non of the references inside the other policysets cannot be resolved.

**Comment by cdanger** [comment]
Only top-level policies may be used in Policy(Set)IdReferences. So make sure that the policy 'checkRoleRegistrerare' is a top-level one (not nested in another one) and that it is loaded before any other policy(set) making reference to it.

**Comment by wwebers** [comment]
That's quiet unfortunate. Seems to be a limitation of Authzforce and it standard policy resolvers, isn't it? I cannot find any such a limitation mentioned in the XACML specification. Only that the mechanism of resolving such a policy reference is out of scope.

**Comment by cdanger** [comment]
Not so much of a limitation for us, because you can always refactor a Policy(Set)IdReference to point to a top-level policy instead of a nested one. 
For example, if you have PolicySet PS1 that contains policy P1 and a policy reference to P1 represented by  `*P1`:

```
PS1:
  P1
  ...
  *P1
```
To work with AuthzForce, just make P1 a top-level policy, i.e. make AuthzForce load both P1 and PS1 as separate policies (you can load as many as you want), and rewrite PS1 as follows:

```
PS1:
  *P1
  *P1
```

Similarly, if you had the policy reference to P1 in another policyset PS2:
```
PS1:
  P1
```
```
PS2:
  *P1
```
... it's even simpler to rewrite PS1 to be AuthzForce-compatible:
```
PS1
  *P1
```

**Comment by wwebers** [comment]
Hi Cyril. Thanks for your answer. But, I'm not quiet sure if I understand what you mean with "top-level-policy". I thought I use only "top-policies". What we try to accomplish is pretty much a setup as the following (each policyset in its own XML file with PS1 as the root policyset):

```
PS1:
  *PS2
  *PS3
  *PS4
  *PS5
  *PS6

PS2:
  P1

PS3:
  *P1
  P2
  P3

PS4:
  *P1
  *P2
  *P3
  P4
  P5
	
PS5:
  *P5
  P6
  P7
  P8
  P9

PS6:
  *P2
  *P8
```

Our PDP configuration is setup as follows:

```
    <refPolicyProvider id="refPolicyProvider" xsi:type="StaticRefPolicyProvider">
        <policyLocation>classpath:PS2.xml</policyLocation>
        <policyLocation>classpath:PS3.xml</policyLocation>
        <policyLocation>classpath:PS4.xml</policyLocation>
        <policyLocation>classpath:PS5.xml</policyLocation>
        <policyLocation>classpath:PS6.xml</policyLocation>
    </refPolicyProvider>
    <rootPolicyProvider id="rootPolicyProvider" xsi:type="StaticRootPolicyProvider" policyLocation="classpath:PS1.xml"/>
```
As far as I understood this should work, shouln't it?

**Comment by cdanger** [comment]
Yes, you got it right for the PolicySets, but you have to do the same for the Policies if they are used in PolicyIdReferences too, i.e. put P1, P2, etc. in separate XML documents (P1.xml, P2.xml, etc.) and add them to the policyLocations. Also for the rootPolicyProvider, instead of the `StaticRootPolicyProvider` (that we plan to deprecate), I recommend to use `StaticRefBasedRootPolicyProvider` - which only needs the root Policy(Set)Id if you add the root PolicySet to the policyLocations in refPolicyProvider as well.

All in all, it should look like this (assuming `PS1` is the actual PolicySetId in policyset PS1):

```xml
<refPolicyProvider id="refPolicyProvider" xsi:type="StaticRefPolicyProvider">
  <policyLocation>classpath:P1.xml</policyLocation>
  <policyLocation>classpath:P2.xml</policyLocation>
  <policyLocation>classpath:P3.xml</policyLocation>
  <policyLocation>classpath:P5.xml</policyLocation>
  <policyLocation>classpath:P8.xml</policyLocation>
  <policyLocation>classpath:PS2.xml</policyLocation>
  <policyLocation>classpath:PS3.xml</policyLocation>
  <policyLocation>classpath:PS4.xml</policyLocation>
  <policyLocation>classpath:PS5.xml</policyLocation>
  <policyLocation>classpath:PS6.xml</policyLocation>
  <policyLocation>classpath:PS1.xml</policyLocation>
</refPolicyProvider>
<rootPolicyProvider id="rootPolicyProvider" xsi:type="StaticRefBasedRootPolicyProvider">
  <policyRef>PS1</policyRef>
</rootPolicyProvider>
```

**Comment by wwebers** [comment]
Now I understand what you mean. Thanks for your help, Cyril. I'll try this alternative.

**Comment by wwebers** [comment]
Works like a charm.

**Comment by cdanger** [comment]
Glad to hear :-)
