### ISSUE TITLE
Incorrectly formed JSON responses when StatusCode is other than "ok" 

### ISSUE THREAD

**Issue by dannyig** [authzforce/core#42]
Hi,
When forcing a syntax error the response received from the Restful-PDP, configured with JSON in/out processors, looks as follows ..
{
    "Status": {
        "StatusCode": {
            "Value": "urn:oasis:names:tc:xacml:1.0:status:syntax-error"
        },
        "StatusMessage": "Invalid Attributes/Attribute element"
    },
    "Decision": "Indeterminate"
}

Shouldn' t the above include the "Response" key ?
Looking at the code indeed both processClientError and processInternalError methods in BaseXacmlJsonResultPostprocessor.java do not seem to add the "Response" key. Is this by design or ia it a defect? 
The same scenario when using a XML payload results in a response which includes the "Response" element. 

Thanks and Regards,

# Software version (AuthzForce Core)
14.0.0

authzforce-ce-jaxrs-utils 
1.3.1

# Platform JRE

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

# Platform OS
Windows 10

# Error stack trace or logs (if any)

--------------------------------------
2019-12-23 22:34:02.163  INFO 31288 --- [nio-8080-exec-7] o.a.c.interceptor.LoggingInInterceptor   : Inbound Message
----------------------------
ID: 4
Address: http://localhost:8080/services/pdp
Encoding: UTF-8
Http-Method: POST
Content-Type: application/json
Headers: {Accept=[*/*], accept-encoding=[gzip, deflate], cache-control=[no-cache], connection=[keep-alive], Content-Legth=[437], content-type=[application/json], host=[localhost:8080], postman-token=[c7806ab6-892e-4f54-ad8f-78b59aefafa7, user-agent=[PostmanRuntime/7.1.1]}
Payload: {
  "Request" : {
    "ReturnPolicyIdList" : false,
    "CombinedDecision" : false,
    "Category" : [ {
      "CategoryId" : "names:tc:xacml:1.0:subject-category:access-subject",
      "Attribute" : [ {
        "AttributeId" : "urn:oasis:names:tc:xacml:1.0:subject:subject-id",
        "IncludeInResult" : false,
        "DataType" : "http://www.w3.org/2001/XMLSchema#in",
        "Value" : 1
      }
     ]
   }
  ]
}
}
--------------------------------------
2019-12-23 22:34:02.169  INFO 31288 --- [nio-8080-exec-7] o.o.a.c.pdp.api.io.BasePdpEngineAdapter  : Invalid or unsupprted input XACML Request syntax

org.ow2.authzforce.core.pdp.api.IndeterminateEvaluationException: Invalid Attributes/Attribute element
        at org.ow2.authzforce.core.pdp.io.xacml.json.XacmlJsonParsingUtils$BaseXacmlJsonAttributesParser.parseAttributs(XacmlJsonParsingUtils.java:289)
        at org.ow2.authzforce.core.pdp.io.xacml.json.XacmlJsonParsingUtils$BaseXacmlJsonAttributesParser.parseAttributs(XacmlJsonParsingUtils.java:197)
        at org.ow2.authzforce.core.pdp.io.xacml.json.SingleDecisionXacmlJsonRequestPreprocessor.process(SingleDecisionacmlJsonRequestPreprocessor.java:177)
        at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPrepocessor.java:261)
        at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPrepocessor.java:55)
        at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:117)
        at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:149)
        at org.ow2.authzforce.rest.pdp.jaxrs.XacmlPdpResource.evaluateJson(XacmlPdpResource.java:90)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:192)
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)              at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
        at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:216)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)             at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)          at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Invalid Attribute '[category='names:tc:xacml:1.0:subject-category:acces-subject', issuer=null, id='urn:oasis:names:tc:xacml:1.0:subject:subject-id']': invalid DataType: 'http://www.w3.org/201/XMLSchema#in'
        at org.ow2.authzforce.core.pdp.api.io.NamedXacmlAttributeParser.getAttributeValueFactory(NamedXacmlAttributePaser.java:53)
        at org.ow2.authzforce.core.pdp.io.xacml.json.XacmlJsonParsingUtils$NamedXacmlJsonAttributeParser.parseNamedAttibute(XacmlJsonParsingUtils.java:185)
        at org.ow2.authzforce.core.pdp.io.xacml.json.XacmlJsonParsingUtils$NamedXacmlJsonAttributeParser.parseNamedAttibute(XacmlJsonParsingUtils.java:62)
        at org.ow2.authzforce.core.pdp.api.io.XacmlRequestAttributeParser.parseNamedAttribute(XacmlRequestAttributeParer.java:125)
        at org.ow2.authzforce.core.pdp.api.io.LaxXacmlAttributeParser.parseNamedAttribute(LaxXacmlAttributeParser.java154)
        at org.ow2.authzforce.core.pdp.io.xacml.json.XacmlJsonParsingUtils$BaseXacmlJsonAttributesParser.parseAttributs(XacmlJsonParsingUtils.java:285)
        ... 65 common frames omitted

2019-12-23 22:34:02.177  INFO 31288 --- [nio-8080-exec-7] o.a.c.interceptor.LoggingOutInterceptor  : Outbound Message
---------------------------
ID: 4
Response-Code: 200
Content-Type: application/json
Headers: {Content-Type=[application/json], Date=[Mon, 23 Dec 2019 20:34:02 GMT]}
Payload: {"Status":{"StatusCode":{"Value":"urn:oasis:names:tc:xacml:1.0:status:syntax-error"},"StatusMessage":"InvalidAttributes/Attribute element"},"Decision":"Indeterminate"}

# Your code and/or AuthzForce-specific configuration file(s)

<?xml version="1.0" encoding="UTF-8"?>
<pdp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://authzforce.github.io/core/xmlns/pdp/7.0"
     version="7.0.0">
    <policyProvider id="rootPolicyProvider" xsi:type="StaticPolicyProvider">
        <policyLocation>classpath:policy.xml</policyLocation>
    </policyProvider>
    <rootPolicyRef>root</rootPolicyRef>
</pdp>

**Comment by dannyig** [comment]
The pdp.xml  does not show properly above so here it is again
<pdp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://authzforce.github.io/core/xmlns/pdp/7.0"
     version="7.0.0">
    <policyProvider id="rootPolicyProvider" xsi:type="StaticPolicyProvider">
        <policyLocation>classpath:policy.xml</policyLocation>
    </policyProvider>
    <rootPolicyRef>root</rootPolicyRef>
</pdp>

**Comment by cdanger** [comment]
That's a bug indeed. As specified in [JSON Profile](https://docs.oasis-open.org/xacml/xacml-json-http/v1.1/os/xacml-json-http-v1.1-os.html#_Toc5116230), it should be wrapped into a `{ "Response": [ ... ] }`. Thanks for reporting this. Will be fixed in next release.
