### ISSUE TITLE
org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath has no effect

### ISSUE THREAD

**Issue by securedimensions** [authzforce/core#70]
# Software version (AuthzForce Core)
21.2.0
# Platform JRE
11
# Platform OS
MAC
# Error stack trace or logs (if any)
The `Request.schema.json` seems not to get loaded from the location specified in the `authzforce-ce.xml` context deployment.
When submitting a JSON request with additional attribute `SRS`, the request is still validated against the schema loaded from `classpath` and not from the configured location.
````
2022-12-01 16:09:36,761|DEBUG|http-nio-8080-exec-2|org.apache.cxf.service.invoker.AbstractInvoker:175|Invoking method public abstract org.json.JSONObject org.ow2.authzforce.rest.api.jaxrs.PdpResource.requestPolicyDecisionXacmlJson(org.json.JSONObject) on object org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl@259f6a82 with params [{"Request":{"CombinedDecision":false,"Category":[{"CategoryId":"urn:oasis:names:tc:xacml:1.0:subject-category:access-subject","Attribute":[{"SRS":"EPSG:4326","AttributeId":"subject-location","Value":"POINT (10 1)","DataType":"urn:ogc:def:dataType:geoxacml:3.0:geometry","IncludeInResult":false}]}],"ReturnPolicyIdList":false}}].|
2022-12-01 16:10:28,510|DEBUG|http-nio-8080-exec-2|org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor:203|{
    "schemaLocation": "classpath://org/ow2/authzforce/xacml/json/model/common-std.schema.json#/definitions/AttributeType",
    "pointerToViolation": "#/Request/Category/0/Attribute/0",
    "causingExceptions": [],
    "keyword": "additionalProperties",
    "message": "extraneous key [SRS] is not permitted"
}|
2022-12-01 16:10:28,512|INFO |http-nio-8080-exec-2|org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter:149|Invalid or unsupported input XACML Request syntax|
org.ow2.authzforce.core.pdp.api.IndeterminateEvaluationException: Invalid Request
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:204)
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:47)
    at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:145)
    at org.ow2.authzforce.core.pdp.api.io.BasePdpEngineAdapter.evaluate(BasePdpEngineAdapter.java:193)
    at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$PdpBundle.evaluate(FlatFileBasedDomainsDao.java:563)
    at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$FileBasedDomainDaoImpl.evaluatePolicyDecision(FlatFileBasedDomainsDao.java:2605)
    at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl.requestPolicyDecisionXacmlJson(DomainResourceImpl.java:270)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
    at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:286)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:286)
    at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
    at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
    at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
    at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
    at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
    at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
    at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:709)
    at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.ow2.authzforce.webapp.ExceptionFilter.doFilter(ExceptionFilter.java:64)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:356)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:870)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1762)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
    at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.everit.json.schema.ValidationException: #/Request/Category/0/Attribute/0: extraneous key [SRS] is not permitted
    at org.everit.json.schema.ValidationException.copy(ValidationException.java:486)
    at org.everit.json.schema.DefaultValidator.performValidation(Validator.java:73)
    at org.everit.json.schema.Schema.validate(Schema.java:152)
    at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonRequestPreprocessor.process(BaseXacmlJsonRequestPreprocessor.java:199)
    ... 52 common frames omitted
````

# Your code and/or AuthzForce-specific configuration file(s)
In `.../Catalina/localhost/authzforce-ce.xml` the following element should define the location of the JSON request schema used for the JSON request validation.
````
<Environment name="org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath" value="GeoXACML/Request.schema.json" type="java.lang.String" override="false"
                 description="Path to JSON schema file for XACML JSON Profile's Request validation, relative to ${org.ow2.authzforce.config.dir} (if undefined/empty value, the Request.schema.json file from authzforce-ce-xacml-json-model project is used by default)" />
````

**Comment by cdanger** [comment]
This does not apply to AuthzFore Core but AuthzForce Server. Please re-create the issue there:
https://github.com/authzforce/server/issues
