### ISSUE TITLE
clientRequestErrorVerbosityLevel > 0 throws startup exception

### ISSUE THREAD

**Issue by securedimensions** [authzforce/core#71]
# Software version (AuthzForce Core)
21.2.0
# Platform JRE
11
# Platform OS
MAC
# Error stack trace or logs (if any)
````
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao]: Constructor threw exception; nested exception is java.lang.RuntimeException: Invalid domain data for domain 'A0bdIbmGEeWhFwcKrC9gSQ'
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
	... 54 common frames omitted
Caused by: java.lang.RuntimeException: Invalid domain data for domain 'A0bdIbmGEeWhFwcKrC9gSQ'
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao.lambda$new$1(FlatFileBasedDomainsDao.java:2786)
	at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl.<init>(DomainResourceImpl.java:136)
	at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl$Factory.getInstance(DomainResourceImpl.java:118)
	at org.ow2.authzforce.rest.service.jaxrs.DomainResourceImpl$Factory.getInstance(DomainResourceImpl.java:99)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao.<init>(FlatFileBasedDomainsDao.java:2779)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
	... 56 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported clientRequestErrorVerbosityLevel: 10. Expected: 0.
	at org.ow2.authzforce.core.pdp.io.xacml.json.BaseXacmlJsonResultPostprocessor.<init>(BaseXacmlJsonResultPostprocessor.java:227)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$PdpBundle.lambda$new$3(FlatFileBasedDomainsDao.java:530)
	at org.ow2.authzforce.core.pdp.impl.io.PdpEngineAdapters.newInoutAdapter(PdpEngineAdapters.java:169)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$PdpBundle.<init>(FlatFileBasedDomainsDao.java:531)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$FileBasedDomainDaoImpl.reloadPDP(FlatFileBasedDomainsDao.java:841)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao$FileBasedDomainDaoImpl.<init>(FlatFileBasedDomainsDao.java:798)
	at org.ow2.authzforce.pap.dao.flatfile.FlatFileBasedDomainsDao.lambda$new$1(FlatFileBasedDomainsDao.java:2782)
	... 64 common frames omitted
````

# Your code and/or AuthzForce-specific configuration file(s)
When increasing the verbosity level for exception responses (I want that "my" error message gets displayed in the Indeterminate response) in `data/domains/A0bdIbmGEeWhFwcKrC9gSQ/pdp.xml` like this
````
<pdp xmlns="http://authzforce.github.io/core/xmlns/pdp/8" xmlns:ns2="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" version="8.0" standardDatatypesEnabled="true" standardFunctionsEnabled="true" standardCombiningAlgorithmsEnabled="true" standardAttributeProvidersEnabled="true" xPathEnabled="false" strictAttributeIssuerMatch="false" maxIntegerValue="2147483647" maxVariableRefDepth="10" maxPolicyRefDepth="10" clientRequestErrorVerbosityLevel="10">
````
the startup produces the following exception which seems to origin from this constructor:
````
	/**
	 * Constructor
	 * 
	 * @param clientRequestErrorVerbosityLevel
	 *            Level of verbosity of the error message trace returned in case of client request errors, e.g. invalid requests. Increasing this value usually helps the clients better pinpoint the
	 *            issue with their Requests. This result postprocessor returns all error messages in the Java stacktrace up to the same level as this parameter's value if the stacktrace is bigger,
	 *            else the full stacktrace.
	 * @throws IllegalArgumentException
	 *             if {@code clientRequestErrorVerbosityLevel < 0}
	 */
	public BaseXacmlJsonResultPostprocessor(final int clientRequestErrorVerbosityLevel) throws IllegalArgumentException
	{
		if (clientRequestErrorVerbosityLevel < 0)
		{
			throw new IllegalArgumentException("Invalid clientRequestErrorVerbosityLevel: " + clientRequestErrorVerbosityLevel + ". Expected: non-negative.");
		}

		if (clientRequestErrorVerbosityLevel > 0)
		{
			throw new IllegalArgumentException("Unsupported clientRequestErrorVerbosityLevel: " + clientRequestErrorVerbosityLevel + ". Expected: 0.");
		}

		this.maxDepthOfErrorCauseIncludedInResult = clientRequestErrorVerbosityLevel;
	}
````
Would the support for `clientRequestErrorVerbosityLevel > 0` be an additional feature to authzforce core?

**Comment by cdanger** [comment]
It is supported for XML responses only. So you may request the response in XML if you want more details: default option with Authzforce Core CLI (and using header `Accept: application/xml` or `Accept: application/xacml+xml` with AuthzForce Server), `clientRequestErrorVerbosityLevel > 0` is mostly for troubleshooting purposes.
